[versions]
paper = "1.21.4-R0.1-SNAPSHOT"
incendo-cloud = "2.0.0"
google-autoservice = "1.1.1"
configurate = "4.2.0"

[libraries]
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
configurate = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate" }
incendo-cloud-core = { module = "org.incendo:cloud-core", version.ref = "incendo-cloud" }
incendo-cloud-annotations = { module = "org.incendo:cloud-annotations", version.ref = "incendo-cloud" }
incendo-cloud-paper = { module = "org.incendo:cloud-paper", version = "2.0.0-SNAPSHOT" }
google-autoservice = { module = "com.google.auto.service:auto-service", version.ref = "google-autoservice" }

[bundles]
incendocloud = ["incendo-cloud-core", "incendo-cloud-annotations", "incendo-cloud-paper"]